name: ramdepth
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - torchvision=0.14.1
  - torchdata
  - pytorch-lightning=1.*
  - kornia
  - imageio
  - scipy
  - matplotlib
  - pandas

  # dev
  - ipython
  - ipykernel
  - black

  - pip
  - pip:
    - pipe
    - cryptography
    - webdataset
    - python-dotenv
    - plyfile
    - pytest